# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-07 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('id',),
                'db_table': 'categorias_productos_terminados',
            },
        ),
    ]
