# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-09 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
        ('proceso', '0001_initial'),
        ('materiaprima', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoTerminado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('costo_produccion', models.FloatField()),
                ('precio_venta', models.FloatField()),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('estado', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorias.Categoria')),
                ('id_detalle_formula', models.ManyToManyField(db_table='detalles_formulas', to='materiaprima.MateriaPrima')),
                ('id_proceso', models.ManyToManyField(db_table='procesos_productos', to='proceso.Proceso')),
            ],
            options={
                'ordering': ('id',),
                'permissions': (('form_view_producto', 'Formulario producto terminado'),),
            },
        ),
    ]
