# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-27 02:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
        ('proceso', '0001_initial'),
        ('materiaprima', '0001_initial'),
        ('presentaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalles_Formulas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=16)),
                ('id_materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiaprima.MateriaPrima')),
            ],
            options={
                'ordering': ('id',),
                'db_table': 'detalles_formulas',
            },
        ),
        migrations.CreateModel(
            name='Procesos_Formulas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proceso.Proceso')),
            ],
            options={
                'ordering': ('id',),
                'db_table': 'procesos_formulas',
            },
        ),
        migrations.CreateModel(
            name='ProductoTerminado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('costo_produccion', models.DecimalField(decimal_places=2, max_digits=16)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=16)),
                ('cantidad_productos', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField()),
                ('estado', models.BooleanField(default=True)),
                ('categoria_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorias.Categoria')),
                ('materia_prima', models.ManyToManyField(through='productos.Detalles_Formulas', to='materiaprima.MateriaPrima')),
                ('presentacion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presentaciones.Presentacion')),
                ('proceso', models.ManyToManyField(through='productos.Procesos_Formulas', to='proceso.Proceso')),
            ],
            options={
                'ordering': ('id',),
                'permissions': (('form_view_producto', 'Formulario producto terminado'),),
            },
        ),
        migrations.AddField(
            model_name='procesos_formulas',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.ProductoTerminado'),
        ),
        migrations.AddField(
            model_name='detalles_formulas',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.ProductoTerminado'),
        ),
    ]
