# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-27 04:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productoterminado',
            old_name='cantidad_productos',
            new_name='cantidad',
        ),
    ]
