# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-13 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoterminado',
            name='stock',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productoterminado',
            name='cantidad',
            field=models.PositiveIntegerField(default=True),
        ),
    ]
