# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-27 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20170927_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoterminado',
            name='costo_produccion',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='productoterminado',
            name='precio_venta',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=16),
        ),
    ]
