# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-14 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_detalles_formulas_cantidad_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalles_formulas',
            name='cantidad_productos',
        ),
        migrations.AddField(
            model_name='productoterminado',
            name='cantidad_productos',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
