# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-27 04:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_auto_20170927_0407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productoterminado',
            old_name='categoria_id',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='productoterminado',
            old_name='presentacion_id',
            new_name='presentacion',
        ),
    ]
