# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-15 03:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presentaciones', '0001_initial'),
        ('productos', '0004_auto_20161214_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoterminado',
            name='presentacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='presentaciones.Presentacion'),
            preserve_default=False,
        ),
    ]
