# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-01 10:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_auto_20170927_0434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productoterminado',
            old_name='categoria',
            new_name='categoria_id',
        ),
        migrations.RenameField(
            model_name='productoterminado',
            old_name='presentacion',
            new_name='presentacion_id',
        ),
    ]
