# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-16 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_productoterminado_presentacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoterminado',
            name='cantidad',
            field=models.PositiveIntegerField(blank=True, default=True),
        ),
    ]
