# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-16 23:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_auto_20171001_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productoterminado',
            old_name='categoria_id',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='productoterminado',
            old_name='presentacion_id',
            new_name='presentacion',
        ),
    ]
