# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-30 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kardex_materia_prima', '0002_auto_20161030_1849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kardexmateriaprima',
            options={'ordering': ('id', 'fecha_vencimiento'), 'permissions': (('form_view_kardexmateriaprima', 'Formulario ejecuci\xf3n kardex materia prima'), ('add_kardexmateriaprima', 'Insertar una ejecuci\xf3n de una kardex materia prima'), ('change_kardexmateriaprima', 'Actualizar una ejecuci\xf3n de una kardex materia prima'), ('delete_kardexmateriaprima', 'Eliminar una ejecuci\xf3n de una kardex materia prima'))},
        ),
    ]
