# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-30 19:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kardex_materia_prima', '0003_auto_20161030_1938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kardexmateriaprima',
            options={'ordering': ('id', 'fecha_vencimiento'), 'permissions': (('form_view_kardexmateriaprima', 'Formulario ejecuci\xf3n kardex materia prima'),)},
        ),
    ]
