# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-30 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_auto_20161030_1852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalle_pedido',
            options={'ordering': ('id',), 'permissions': (('form_view_pedido', 'Formulario pedido'), ('add_pedido', 'Insertar un pedido'), ('change_pedido', 'Actualizar un pedido'), ('delete_pedido', 'Eliminar un pedido'))},
        ),
    ]
