# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-08 08:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedore',
            old_name='nombre_empresa',
            new_name='empresa',
        ),
    ]
