# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-30 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_auto_20161030_1849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedore',
            options={'ordering': ('id',), 'permissions': (('form_view_proveedore', 'Formulario proveedor'), ('add_proveedore', 'Insertar un proveedor'), ('change_proveedore', 'Actualizar un proveedor'), ('delete_proveedore', 'Eliminar un proveedor'))},
        ),
    ]
