# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-06 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0003_auto_20160605_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedore',
            name='fax',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='proveedore',
            name='nombre_contacto',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proveedore',
            name='telefono_contacto',
            field=models.CharField(max_length=15),
        ),
    ]
