# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-11 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0004_auto_20160606_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedore',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
