# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-05 22:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoriasmateriaprima', '0001_initial'),
        ('unidadesmedida', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('cantidad_entrada', models.FloatField()),
                ('cantidad', models.FloatField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categoriasmateriaprima.CategoriaMateriaPrima')),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unidadesmedida.UnidadesMateriaPrima')),
            ],
        ),
    ]
