# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-08 00:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoriasmateriaprima', '0001_initial'),
        ('unidadesmedida', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=16)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categoriasmateriaprima.CategoriaMateriaPrima')),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unidadesmedida.UnidadMedida')),
            ],
            options={
                'ordering': ('id',),
                'db_table': 'materias_primas',
                'permissions': (('form_view_materiaprima', 'Puede ver el formulario de materia prima'),),
            },
        ),
    ]
