# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-13 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiaprima', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiaprima',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='cantidad',
            field=models.DecimalField(blank=True, decimal_places=2, default=True, max_digits=16),
        ),
    ]
