# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-30 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiaprima', '0002_auto_20161030_1852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materiaprima',
            options={'ordering': ('id',), 'permissions': (('form_view_materiaprima', 'Formulario materia prima'),)},
        ),
    ]
