# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-30 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiaprima', '0003_auto_20161030_1859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materiaprima',
            options={'ordering': ('id',), 'permissions': (('form_view_materiaprima', 'Formulario materia prima'), ('add_materiaprima', 'Insertar una materia prima'), ('change_materiaprima', 'Actualizar una materia prima'), ('delete_materiaprima', 'Eliminar una materia prima'))},
        ),
    ]
