# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-30 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiaprima', '0004_auto_20161030_1938'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='materiaprima',
            table='materiasprimas',
        ),
    ]
