# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-30 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiaprima', '0005_auto_20161030_1940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materiaprima',
            options={'ordering': ('id',), 'permissions': (('form_view_materiaprima', 'Formulario materia prima'), ('ad_materiaprima', 'Insertar una materia prima'), ('update_materiaprima', 'Actualizar una materia prima'), ('delet_materiaprima', 'Eliminar una materia prima'))},
        ),
    ]
