# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-30 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        ('ejecucion_orden', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KardexProductoTerminado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_movimiento', models.DateTimeField()),
                ('tipo_movimiento', models.BooleanField()),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=16)),
                ('valor_unitario', models.DecimalField(decimal_places=3, max_digits=16)),
                ('total', models.DecimalField(decimal_places=3, max_digits=16)),
                ('lote', models.CharField(max_length=30)),
                ('fecha_vencimiento', models.DateTimeField()),
                ('id_ejecucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ejecucion_orden.EjecucionOrden')),
                ('producto_terminado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.ProductoTerminado')),
            ],
            options={
                'ordering': ('id', 'fecha_vencimiento'),
                'db_table': 'kardex_productos_terminados',
                'permissions': ('form_view_kardex_producto', 'Puede ver el formulario de kardex producto terminado'),
            },
        ),
    ]
