# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-30 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kardex_producto_terminado', '0002_auto_20161030_1849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kardexproductoterminado',
            options={'ordering': ('id', 'fecha_vencimiento'), 'permissions': (('form_view_kardexproductoterminado', 'Formulario ejecuci\xf3n kardex producto terminado'), ('add_kardexproductoterminado', 'Insertar una ejecuci\xf3n de una kardex producto terminado'), ('change_kardexproductoterminado', 'Actualizar una ejecuci\xf3n de una kardex producto terminado'), ('delete_kardexproductoterminado', 'Eliminar una ejecuci\xf3n de una kardex producto terminado'))},
        ),
    ]
