# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-07 02:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maquina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('tiempo', models.TimeField()),
                ('estado', models.BooleanField(default=True)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maquina.Maquina')),
            ],
            options={
                'ordering': ('id',),
                'db_table': 'procesos',
                'permissions': (('form_view_proceso', 'Formulario proceso'),),
            },
        ),
    ]
