# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-30 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proceso', '0002_auto_20161030_1849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proceso',
            options={'ordering': ('id',), 'permissions': (('form_view_proceso', 'Formulario proceso'), ('add_proceso', 'Insertar un proceso'), ('change_proceso', 'Actualizar un proceso'), ('delete_proceso', 'Eliminar un proceso'))},
        ),
    ]
