# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-30 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unidadesmedida', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('capacidad', models.DecimalField(decimal_places=3, max_digits=16)),
                ('tiempo', models.TimeField(max_length=15)),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unidadesmedida.UnidadMedida')),
            ],
            options={
                'ordering': ('id',),
                'db_table': 'maquinas',
                'permissions': (('form_view_maquina', 'Puede ver el formulario de maquinas'),),
            },
        ),
    ]
