# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-27 02:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unidadesmedida', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('capacidad', models.DecimalField(decimal_places=2, max_digits=16)),
                ('estado', models.BooleanField(default=True)),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unidadesmedida.UnidadMedida')),
            ],
            options={
                'ordering': ('id',),
                'db_table': 'maquinas',
                'permissions': (('form_view_maquina', 'Formulario maquina'),),
            },
        ),
    ]
