# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-30 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maquina', '0002_auto_20161030_1852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maquina',
            options={'ordering': ('id',), 'permissions': (('form_view_maquina', 'Formulario maquina'), ('add_maquina', 'Insertar una maquina'), ('change_maquina', 'Actualizar una maquina'), ('delete_maquina', 'Eliminar una maquina'))},
        ),
    ]
