# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-09 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        ('orden_produccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EjecucionOrden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('cantidad', models.PositiveIntegerField()),
                ('estado', models.BooleanField(default=True)),
                ('id_orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orden_produccion.OrdenProduccion')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.ProductoTerminado')),
            ],
            options={
                'ordering': ('id',),
                'db_table': 'ejecucion_ordenes',
                'permissions': (('form_view_ejecucion_orden', 'Formulario ejecuci\xf3n orden producci\xf3n'),),
            },
        ),
    ]
