# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-30 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejecucion_orden', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ejecucionorden',
            options={'ordering': ('id',), 'permissions': (('form_view_ejecucion', 'Puede ver el formulario de ejecuci\xf3n ordenes de produccion'),)},
        ),
    ]
