# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-30 18:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejecucion_orden', '0002_auto_20161030_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ejecucionorden',
            options={'ordering': ('id',)},
        ),
    ]
