# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-30 19:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejecucion_orden', '0003_auto_20161030_1849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ejecucionorden',
            options={'ordering': ('id',), 'permissions': (('form_view_ejecucion_orden', 'Formulario ejecuci\xf3n orden producci\xf3n'),)},
        ),
    ]
