# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-30 19:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejecucion_orden', '0005_auto_20161030_1909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ejecucionorden',
            options={'ordering': ('id',), 'permissions': (('form_view_ejecucion_orden', 'Formulario ejecuci\xf3n orden producci\xf3n'), ('add_ejecucionorden', 'Insertar una ejecuci\xf3n de una orden de producci\xf3n'), ('change_ejecucionorden', 'Actualizar una ejecuci\xf3n de una orden de producci\xf3n'), ('delete_ejecucionorden', 'Eliminar una ejecuci\xf3n de una orden de producci\xf3n'))},
        ),
    ]
