# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-15 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0002_auto_20160515_0837'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoTerminado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('costo_produccion', models.FloatField()),
                ('precio_venta', models.FloatField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorias.Categoria')),
            ],
        ),
    ]
