# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-10 02:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_productoterminado_cantidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productoterminado',
            options={'ordering': ('id',), 'permissions': (('form_view_producto', 'M\xf3dulo Productos'),)},
        ),
    ]
