# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-09 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('equivalencia', models.DecimalField(decimal_places=3, max_digits=16)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('id',),
                'db_table': 'unidades_de_medidas',
                'permissions': (('form_view_unidadmedida', 'Formulario unidades de medidas'),),
            },
        ),
    ]
