# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-08 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('equivalencia', models.DecimalField(decimal_places=3, max_digits=16)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ('id',),
                'db_table': 'unidades_de_medidas',
                'permissions': ('form_view_unidadmedida', 'Puede ver el formulario de unidades de medidas'),
            },
        ),
    ]
