# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-30 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unidadesmedida', '0002_auto_20161030_1852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unidadmedida',
            options={'ordering': ('id',), 'permissions': (('form_view_unidadmedida', 'Formulario unidades de medidas'), ('add_unidadmedida', 'Insertar una unidad de medida'), ('change_unidadmedida', 'Actualizar una unidad de medida'), ('delete_unidadmedida', 'Eliminar una unidad de medida'))},
        ),
    ]
